# databases と services は、トップレベルで定義される別々のセクションです。

databases:
  # PostgreSQLデータベースの定義
  - name: furniture-db
    plan: free

# Webサービスや静的サイトの定義
services:
  # 1. Vue3 フロントエンド (静的サイトとして定義)
  #    静的サイトは「type: web」と「runtime: static」を組み合わせます。
  - type: web
    name: furniture-web
    plan: free
    runtime: static # これで静的サイトとして扱われます
    rootDir: ./frontend
    buildCommand: "npm install && npm run build"
    publishPath: "dist" # ビルド成果物が出力されるディレクトリ
    # autoDeployはデフォルトでtrueなので、必要に応じてfalseに設定できます

  # 2. Flask バックエンド (Web Service)
  - type: web
    name: furniture-api
    plan: free
    runtime: docker # Dockerfileを使うことを明示します
    rootDir: ./backend
    # DockerfileのCMDをGunicornで上書きして起動します
    startCommand: "gunicorn --bind 0.0.0.0:10000 app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: furniture-db # 上で定義したデータベース名
          property: connectionString
      - key: FRONTEND_URL
        fromService:
          type: web # フロントエンドもtype: webです
          name: furniture-web
          property: url