# render.yaml
databases:
  - name: furniture-db
    # plan やサイズは必要に応じて
    # plan: free

services:
  # ===== Backend (Flask) =====
  - type: web
    name: furniture-backend
    runtime: docker
    rootDir: backend
    dockerfilePath: ./backend/Dockerfile
    autoDeploy: true
    # Flask は 0.0.0.0:$PORT で listen すること（Dockerfile/起動コマンド側で設定）

    envVars:
      # Render Postgres の外部接続文字列を注入
      - key: DATABASE_URL
        fromDatabase:
          name: furniture-db
          property: connectionString
      # 必要に応じて追加
      # - key: FLASK_ENV
      #   value: production
      # - key: SECRET_KEY
      #   generateValue: true

  # ===== Frontend (Vue 3 / Vite を Static Site として配信) =====
  - type: web
    name: furniture-frontend
    runtime: static
    rootDir: frontend
    buildCommand: |
      npm ci
      npm run build
    staticPublishPath: dist
    autoDeploy: true

    # SPA のための 404 回避（必要なければ削除）
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

    envVars:
      # フロントで API ベース URL を使う場合は、手動で設定してください
      # （Static Site から他サービスの「URL」は参照できないため）
      - key: VITE_API_BASE
        sync: false   # 初回デプロイ時にダッシュボードで入力（例: https://<backend>.onrender.com）
