# render.yaml (修正版)

# 最初にデータベースを定義するトップレベルのセクション
databases:
  - name: furniture-db
    plan: free
    postgresMajorVersion: 14

# 次にサービス（Webアプリ、静的サイト）を定義するトップレベルのセクション
services:
  # 1. Flask バックエンド (Web Service)
  - type: web
    name: furniture-api
    plan: free
    rootDir: ./backend
    startCommand: "gunicorn --bind 0.0.0.0:5000 app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1
      - key: DATABASE_URL
        fromDatabase: # ★★★ "fromService" ではなく "fromDatabase" を使います
          name: furniture-db # 上で定義したデータベース名を指定
          property: connectionString
      - key: FRONTEND_URL
        fromService:
          type: static
          name: furniture-web
          property: url

  # 2. Vue3 フロントエンド (Static Site)
  - type: static
    name: furniture-web
    plan: free
    rootDir: ./frontend
    buildCommand: "npm install && npm run build"
    publishPath: "./dist"
    envVars:
      - key: VITE_APP_API_URL
        fromService:
          type: web
          name: furniture-api
          property: url