"""create funiture model and schema

Revision ID: e2eb5b719256
Revises: eb367162206b
Create Date: 2025-08-04 15:36:50.320041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2eb5b719256'
down_revision = 'eb367162206b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('furnitures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('furnitures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_furnitures_color'), ['color'], unique=False)
        batch_op.create_index(batch_op.f('ix_furnitures_featured'), ['featured'], unique=False)
        batch_op.create_index(batch_op.f('ix_furnitures_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_furnitures_price'), ['price'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('furnitures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_furnitures_price'))
        batch_op.drop_index(batch_op.f('ix_furnitures_name'))
        batch_op.drop_index(batch_op.f('ix_furnitures_featured'))
        batch_op.drop_index(batch_op.f('ix_furnitures_color'))

    op.drop_table('furnitures')
    # ### end Alembic commands ###
